### ISSUE TITLE
New Option to hide only "Youtube" button

### ISSUE THREAD

**Issue by hashbeerap** [triniwiz/nativescript-youtubeplayer#10]
First of all, thank you for your youtube-player.

Is it possible to only hide "Youtube" button/logo from player control?

On android tried to change player style like:

youtubePlayer.nativeElement.playerStyle = 2; // which show minimum contorls

but no option to exit from fullscreen. Is any way to only hide "Youtube" button?

Thanks in advance.

**Comment by triniwiz** [comment]
You will need to use no controls then create a custom player

**Comment by rg777** [comment]
@triniwiz  Can you suggest please suggest how to do it?

**Comment by triniwiz** [comment]
Available on `@triniwiz/nativescript-youtubeplayer`
