### ISSUE TITLE
Unable to play video inline ... iOS (possibly on Android??)

### ISSUE THREAD

**Issue by BallisticPain** [triniwiz/nativescript-youtubeplayer#11]
So in the attempt to write a `command` controlled video player (such as old DnD Games and a 2d paintball game I played as a teenager), I wanted to remove the controls and have the video play inline. This would allow my user to type commands into the command box and control the video. I was unable to get the video to play inline. Below is what I tried to make this happen.

I attempted to use the `options` which referred to the [player parameters](https://developers.google.com/youtube/player_parameters) from YouTube's iFrame Api in an attempt to set `playsinline`. This didn't work for me. I saw no change.
I then noticed as part of the API for the plugin @triniwiz has a `toggleFullscreen` method and `isFullscreen` property. I tried those, and to no avail. 

Further to attempt to prove I was doing something wrong, I decided to try both the `demo` and `demo-ng` apps. `demo-ng` would play fullscreen just as I was experiencing in my own app. `demo` (might have played if I could get it to work) had issues with the size of the control. It was squishing all of the `buttons` to the bottom so you couldn't actually click on any of them. Being that I was in iOS, I could only play a couple of the videos on the list.

Oh yea, for my actual real-life device, I was using my iPhone X updated to the latest iOS software, which at the time of writing this ticket is: `11.2.1`

**Android Note**
So I don't have an Android device to test on, and right at the moment, I cannot recall if I have even attempted it in the emulator.

**Comment by triniwiz** [comment]
So you are trying to create a custom player with your own controls ? If so then you need to set the controls to 0

**Comment by triniwiz** [comment]
Available on `@triniwiz/nativescript-youtubeplayer`
