### ISSUE TITLE
Multiple players don't work on Android 

### ISSUE THREAD

**Issue by bachras** [triniwiz/nativescript-youtubeplayer#13]
Hi,

I am unable to display multiple youtube players on Android. It seems that every single player requires unique youtube API key. Here is more information about the problem: https://discourse.nativescript.org/t/nativescript-youtubeplayer-plugin-doesnt-work-on-android/4140 .

I am not sure if new feature has to be added to plugin, but is so I am looking forward to it as it is crucial to my app. Thank you once again for plugin.

**Comment by umair-ameen** [comment]
Did you find any solution? Any other plugin?

**Comment by rg777** [comment]
Any update on this issue?

**Comment by Emanuele-Fortunati** [comment]
That's a YouTube thing, you'll have to use multiple keys I'm afraid

**Comment by triniwiz** [comment]
fixed in `@triniwiz/nativescript-youtube`
