### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by dennis-montana** [triniwiz/nativescript-youtubeplayer#16]
Is it possible to release a new version of the plugin?
Then we can use it with the fix from the latest pull request (https://github.com/triniwiz/nativescript-youtubeplayer/pull/14).
Thanks!

**Comment by triniwiz** [comment]
Done https://github.com/triniwiz/nativescript-youtubeplayer/commit/70ce6f8cac661f56c51459473a0ac1d10587ef4b

**Comment by dennis-montana** [comment]
When I download the latest version with NPM (2.2.6), the change from the pull request isn't in there. In the master branch on GitHub we can see the change, but when downloaded the change is not in the src/youtubeplayer.android.js file.
Are you sure you published the version with this change?
