### ISSUE TITLE
NativeScript youtube player "Cannot read property 'getFragmentManager' of undefined".

### ISSUE THREAD

**Issue by culunvb** [triniwiz/nativescript-youtubeplayer#17]
HI all,
Anyone can help me, I got this error in NativeScript youtube player "Cannot read property 'getFragmentManager' of undefined".

Please help me about this issue
I've the package json like this :
"tns-android": {
"version": "3.4.1"
}
"tns-core-modules": "~3.4.0"
C.L.I : 3.4.2

Thank's for your help

**Comment by umair-ameen** [comment]
Found any solution?

**Comment by budi7** [comment]
any solution guys?

**Comment by budi7** [comment]
Well, i found workaround to overcome this issue.

The error occurred at youtubeplayer.android.js line 20
`var manager = app.android.foregroundActivity.getFragmentManager();`

the app.android.foregroundActivity is returning undefined, so thats why it's not possible to call getFragmentManager() from it.

So, here's the quick trick (as on https://github.com/NativeScript/NativeScript/issues/5307)
Create base page and then route ($navigateTo(yourYoutubeplayerPage)) and this plugin will work.

Hope that helps

-------------------------------------------
plugin:
nativescript-youtubeplayer: 2.2.6

core: 
nativescript-vue : 1.3.1
tns-core: 3.4.1

**Comment by triniwiz** [comment]
fixed on `@triniwiz/nativescript-youtubeplayer`
