### ISSUE TITLE
Error: Cannot read property 'player' of undefined

### ISSUE THREAD

**Issue by umair-ameen** [triniwiz/nativescript-youtubeplayer#19]
I am using latest version of nativescript + angular. Implementing this plugin as mentioned in your documentation but still getting Error: "Cannot read property 'player' of undefined"

Exception copy/paste:

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: Cannot read property 'player' of undefined
File: "file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/nativescript-youtubeplayer/youtubeplayer.js, line: 23, column: 56

StackTrace: 
	Frame: function:'YoutubePlayer.createNativeView', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/nativescript-youtubeplayer/youtubeplayer.js', line: 23, column: 57
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 492, column: 35
	Frame: function:'', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
	Frame: function:'', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
	Frame: function:'', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 588, column: 24
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/com.entertainmentproduction.tamilserials/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
	at com.tns.Runtime.callJSMethod(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:954)
	at com.tns.Runtime.callJSMethod(Runtime.java:946)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
	at android.app.Fragment.performCreateView(Fragment.java:2053)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:834)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by yclau** [comment]
i also meet this error .

**Comment by JaganJonnala** [comment]
+1

**Comment by tahirawais1** [comment]
+1

**Comment by rg777** [comment]
Any updates on this?

**Comment by felipebueno** [comment]
Can you create a sample project with this error so we can try and find the bug?

**Comment by cloudSchulze** [comment]
Do you have removed your platform? I got the same error and after removing and adding the platform it works.

**Comment by DSimonovski** [comment]
Can confirm removing the platform and performing a clean build worked out well :)

**Comment by gogoout** [comment]
Run `tns platform clean android` should work.

**Comment by arLevi** [comment]
none of the above works for me ...

Edit: found the issue, when I installed via `tns plugin add nativescript-youtubeplayer` it downloaded the 2.x version instead of the newer version.
So i just forced the latest: `tns plugin add nativescript-youtubeplayer@latest`

**Comment by Bezlepkin** [comment]
I have some error....

**Comment by triniwiz** [comment]
fixed on `@triniwiz/nativescript-youtubeplayer`
