### ISSUE TITLE
cant play multiple different videos  on same page 

### ISSUE THREAD

**Issue by sokolej33** [triniwiz/nativescript-youtubeplayer#21]
I have Angular Nativescript app with listview page that holds multiple YoutubePlayer videos on page.
When have multiple Youtube Player instances, player has its own videourl and the same api key as input. All videos are the same. I think it takes the first url, but inputs for url on each youtube player as inputs are different. Is api key for youtube unique per youtube instance or must each have its own api key? It appear like it is some kind of singelton instance per app.

**Comment by ghost** [comment]
@triniwiz any update on this one? any workaround? cause it can't go further because of this issue.

**Comment by nlantoing** [comment]
Same situation for me, I want to display 2 videos on the same page but I can't for the exact same reason.

**Comment by triniwiz** [comment]
Did some digging the youtube player only allows a single player per activity but I came across this => [view](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubeThumbnailView) so for multiple videos you will use that and have the player as a detail page

**Comment by johnny-stevie** [comment]
@triniwiz I don't really know what to do with this link in your answer, could you elaborate? Also, sometimes i can display multiple videos if add src = "{{id}}" instead of src = "id" but it only displays the same video repeatedly

**Comment by EdJones** [comment]
I'm doing this in nativescript-vue. Each video is in a cardview.
```
<card-view id="card3" class="cardStyle" margin="10" elevation="40" radius="1" @tap="cardDetail3">
            <stack-layout class="cardContent">
              <gridlayout columns="*,20" rows="auto,auto">
                <label text="We're Just Not Wired to Read" class="card-title"></label>
                <label :class="dot3" row="0" col="1" colSpan="1"></label>
              </gridlayout>
              <StackLayout>
                <YoutubePlayer ref="player" src="wlYZBi_07vk" apiKey="AIza..." height="160" />

                <label text="Explore what modern brain scanners show us about reading." class="card-text"></label>
              </StackLayout>

            </stack-layout>
          </card-view>
```

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
