### ISSUE TITLE
Video will be played one second only

### ISSUE THREAD

**Issue by cloudSchulze** [triniwiz/nativescript-youtubeplayer#28]
Hi,
i add your component like this:

`<FlexboxLayout *ngIf="!edit" class="message-img"
            justifyContent="center"
            alignItems="center">
                <Image stretch="aspectFill"  
                    *ngIf="dataFormGroup.get('image').value" 
                    width="100%"        
                    height="100%"
                    [src]="dataFormGroup.get('imgSrc').value">
                </Image>
                <YoutubePlayer     
                *ngIf="!dataFormGroup.get('image').value"                 
                apiKey="XXXXXX" 
                [src]="dataFormGroup.get('youtube').value" 
                height="100%"   
                ></YoutubePlayer>                                           
</FlexboxLayout>           `

I started my app and the video in your component was loaded. The issue i found is that the video will be played for one second and than it stops. After starting the video again it stops after a second. That's ... not optimal ;D.

If i start the video in maximize mode, it will be played normaly. Can you have a look on it? It's a show stopper on my side, because my customer wants this fucntionality.

**Comment by cloudSchulze** [comment]
My dependencies:

```
"dependencies": {
    "@angular/animations": "~6.0.6",
    "@angular/common": "~6.0.6",
    "@angular/compiler": "~6.0.6",
    "@angular/core": "~6.0.6",
    "@angular/forms": "~6.0.6",
    "@angular/http": "~6.0.6",
    "@angular/platform-browser": "~6.0.6",
    "@angular/platform-browser-dynamic": "~6.0.6",
    "@angular/router": "~6.0.6",
    "@nstudio/nativescript-camera-plus": "1.0.6",
    "angular2-uuid": "^1.1.1",
    "font-awesome": "^4.7.0",
    "moment": "^2.22.2",
    "nativescript-angular": "~6.0.6",
    "nativescript-camera": "^4.0.2",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-mediafilepicker": "^1.0.7",
    "nativescript-modal-datetimepicker": "^1.1.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-plugin-firebase": "7.1.2",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-listview": "3.7.2",
    "nativescript-ui-sidedrawer": "^4.3.1",
    "nativescript-videoplayer": "^4.2.0",
    "nativescript-videorecorder": "^3.0.0-alpha.11",
    "nativescript-youtubeplayer": "3.0.1",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.1.0",
    "tns-core-modules": "^4.2.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.1.3",
    "@ngtools/webpack": "6.1.0-rc.0",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.14.4",
    "typescript": "~2.7.2"
  },
```

**Comment by rjgpereira** [comment]
Hi @ableschulze ! not sure if this is related, but I had a similar issue trying to display an embedded video in a webview. I was using [ngSwitch] to hide and show some elements, and that was causing it (dunno why). As soon as I changed the ngSwitch approach to using conditional "visibility", the problem was solved. Maybe it has something to do with that "ngIf", don't know.. just a guess.
Good luck!

**Comment by rjgpereira** [comment]
Hi @ableschulze ! not sure if this is related, but I had a similar issue trying to display an embedded video in a webview. I was using [ngSwitch] to hide and show some elements, and that was causing it (dunno why). As soon as I changed the ngSwitch approach to using conditional "visibility", the problem was solved. Maybe it has something to do with that "ngIf", don't know.. just a guess.
Good luck!

**Comment by triniwiz** [comment]
ios ?

**Comment by cloudSchulze** [comment]
android :(

**Comment by bachras** [comment]
I am having same problem

**Comment by Emanuele-Fortunati** [comment]
That's because you are overlaying the player in some way with other graphical elements, so YT stops the video (you can find it by caching the error events). Sometimes it is just because paddings or margins.

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
