### ISSUE TITLE
Android - Only 1 video plays

### ISSUE THREAD

**Issue by glen-stephens** [triniwiz/nativescript-youtubeplayer#3]
On ios, I can navigate to the player page and set the src multiple times, and the each time a new video loads.  On Android, same code and only the first video loads, subsequent videos leave the player empty only showing the background color.  I am using binding to get the videoId: 

`src="{{ videoId }}"`

**Comment by triniwiz** [comment]
Fixed 😃

**Comment by glen-stephens** [comment]
@triniwiz Thanks for fixing it.  HOWEVER, there is an issue on iOS now.  When I run on iOS with your plugin it requires the npm module which hauls down 300 modules.

`npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/vendor/resize`

Blows things sky high when trying to run on an iOS device.  It jacks things up related to certificates and provisioning profiles.  This is from the IDEDistribution log:  

`Found platform <DVTPlatform:0x7ff9ffc59990:'com.apple.platform.macosx':<DVTFilePath:0x7ff9ffc59920:'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform'>> and cert <DVTSigningCertificate: 0x7ffa06043de0; name='Developer ID Application: Apple Inc. - XQuartz (NA574AWV7E)'`

It calls out the platform macosx which tries to bring along a cert that is not valid.

**Comment by triniwiz** [comment]
This plugin has no npm dep it has dev dep and non of them are related to the one you mentioned you can check he [package.json](https://github.com/triniwiz/nativescript-youtubeplayer/blob/master/src/package.json)

**Comment by glen-stephens** [comment]
So here is the weird thing.  If the plugin is not installed but it's in my package.json dependencies, when I run iOS it adds your plugin PLUS npm module.  Once it brings that along for the ride, causes all kinds of certificate issues.  I checked your package.json file and didn't see a npm module dependency, but your plugin is definitely the one that when added to my project makes nativescript include npm in the project as well. Here is my dependency list.  I installed them one at a time to figure out which one does it and it is definitely yours.

`"dependencies": {
    "base64-js": "^1.2.1",
    "buffer": "^5.0.7",
    "crypto-js": "^3.1.9-1",
    "nativescript-calendar": "^1.2.2",
    "nativescript-cardview": "^2.0.2",
    "nativescript-fingerprint-auth": "^5.0.0",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-orientation": "^2.0.1",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-pro-ui": "^3.2.0",
    "nativescript-pulltorefresh": "^2.0.2",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-youtubeplayer": "^2.2.3",
    "tns-core-modules": "^3.3.0"
  }`

I also verified that if I run tns plugin install nativescript-youtubeplayer, the npm module is also installed.
