### ISSUE TITLE
Player Height Issue

### ISSUE THREAD

**Issue by sarfraznawaz2005** [triniwiz/nativescript-youtubeplayer#30]
Thanks for nice library!

I am having height issue. This is player with 200 height:

![screenshot_20181124-221029](https://user-images.githubusercontent.com/201788/48971042-b297e780-f036-11e8-9c9d-ba9cf351b8f3.png)

This is player with 300 height:

![screenshot_20181124-221139](https://user-images.githubusercontent.com/201788/48971045-bdeb1300-f036-11e8-9a58-7462f21e4443.png)

I actually want to increase actual player height but changing height property of the player just increases space around it (gray area) not the actual player or video height.

Can you please tell how can I increase height of actual video?

Thanks

**Comment by sarfraznawaz2005** [comment]
In our app this is the only issue left, once solution for this is found, we will publish our app to play store.

Waiting to hear soon. Thanks

**Comment by felipebueno** [comment]
@sarfraznawaz2005 Now that you have time, maybe you should help solving this issue.

**Comment by sarfraznawaz2005** [comment]
@felipebueno I would love to but I am new to NativeScript unfortunately.

**Comment by triniwiz** [comment]
Can you all leave your version info

**Comment by sarfraznawaz2005** [comment]
@triniwiz Thanks for reply!

FYI, I am using Android.

I am using tns version `5.0.1`, here is package.json file details:

```
  "dependencies": {
    "nativescript-fresco": "^5.1.0",
    "nativescript-sqlite": "^2.2.3",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~5.0.0",
    "nativescript-youtubeplayer": "^3.0.1",
    "randomcolor": "^0.5.3",
    "rxjs": "~6.3.0",
    "tns-core-modules": "~5.0.2"
  },
  "devDependencies": {
    "eslint": "~5.8.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-webpack": "~0.18.0"
  },
```

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
