### ISSUE TITLE
Youtube player not playing 

### ISSUE THREAD

**Issue by ghost** [triniwiz/nativescript-youtubeplayer#34]
When I put the propert "options" youtube videos not playing anymore.

**Comment by Emanuele-Fortunati** [comment]
Same here: it is due to the wrong format of the options, but still I cannot figure out how to pass options in the right format

**Comment by johnny-stevie** [comment]
How do you even give options to the player? Do you just add a boolean parameter in the html?

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
