### ISSUE TITLE
i am getting 

### ISSUE THREAD

**Issue by dkandari** [triniwiz/nativescript-youtubeplayer#38]
my project is not running if i am using this plugin.
i am running letest nativscript software with angular.

 Error calling module function

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-youtu
beplayer/angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:553)
    com.tns.Runtime.run(Runtime.java:545)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:102
5)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5505)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:163)
    android.app.ActivityThread.main(ActivityThread.java:6228)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:9
04)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
File: "<unknown>, line: 1, column: 265

StackTrace:
        Frame: function:'require', file:'', line: 1, column: 266
        Frame: function:'', file:'file:///data/data/org.nativescript.preview/fil
es/app/app/app.module.js', line: 6, column: 17
        Frame: function:'require', file:'', line: 1, column: 266
        Frame: function:'', file:'file:///data/data/org.nativescript.preview/fil
es/app/main.js', line: 5, column: 20
        Frame: function:'require', file:'', line: 1, column: 266

**Comment by johnny-stevie** [comment]
Is this when you run it on nativescript playground or just on the emulator?

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
