### ISSUE TITLE
No View found error

### ISSUE THREAD

**Issue by leocrawf** [triniwiz/nativescript-youtubeplayer#40]
I am having this error no matter how I clean the platforms folder:

System.err: java.lang.IllegalArgumentException: No view found for id 0x8 (unknown) for fragment YouTubePlayerFragment{68324b4 #1 id=0x8 TNSYoutubeFragment}
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:987)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
System.err: 	at android.app.BackStackRecord.run(BackStackRecord.java:815)
System.err: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
System.err: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by Puru0911** [comment]
If I open youtube in modal I'm having this error why?

**Comment by mpht** [comment]
having the same issue here (using the youtubeplayer inside a modal)
works fine on iOS.
same error as above on android.

**Comment by sanved77** [comment]
This is because the modal cannot access the root view. It itself is a view being drawn in the top of the app. If you can use it under a <Frame> and just call a page using navigation then it will work.

**Comment by andresilva-cc** [comment]
> This is because the modal cannot access the root view. It itself is a view being drawn in the top of the app. If you can use it under a and just call a page using navigation then it will work.

I'm not using it inside a modal, but inside a component that is displayed inside a TabContentItem (from Tabs component). The strange thing is that if I remove the player from the component, hot reload it, add it again, hot reload again, it works. Is there any workaround for this?

If it helps: I'm using NativeScript-Vue.

**Comment by andresilva-cc** [comment]
> > This is because the modal cannot access the root view. It itself is a view being drawn in the top of the app. If you can use it under a and just call a page using navigation then it will work.
> 
> I'm not using it inside a modal, but inside a component that is displayed inside a TabContentItem (from Tabs component). The strange thing is that if I remove the player from the component, hot reload it, add it again, hot reload again, it works. Is there any workaround for this?
> 
> If it helps: I'm using NativeScript-Vue.

I could solve this problem by adding a "v-if" directive to the YoutubePlayer component, bound to a variable named 'ready' that I set to true when the StackLayout (root of the component) loaded event is fired.

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
