### ISSUE TITLE
Status bar disappearing on iOS

### ISSUE THREAD

**Issue by dennis-montana** [triniwiz/nativescript-youtubeplayer#41]
Since we upgrades to NativeScript 5.1 we have an issue with the status bar on iOS using the Youtube player.
When we play a video in full screen and close the video, the status bar has disappeared and never returns until we restart the app.
I've tested this with a simple NativeScript template app from the market place and was able to reproduce it directly.

The versions we're using:
Platform iOS 5.1.1
NativeScript Angular 7.1
NativeScript CLI 5.1

Any help would be appreciated.

Edit, this looks like the same issue:
https://stackoverflow.com/questions/52136497/status-bar-disappeared-after-full-screen-video-in-wkwebview-only-in-ios-12

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
