### ISSUE TITLE
YouTubeAndroidPlayerApi.jar

### ISSUE THREAD

**Issue by mpht** [triniwiz/nativescript-youtubeplayer#43]
In case anyone experiences the same error:
On android (tns-android: 5.2.1) there is an error during **createNativeView**. com.**google**.android.youtube.player.YouTubePlayerFragment.newInstance() (google is not defined)

It turns out the YouTubeAndroidPlayerApi.jar needs to be added to
**.../your-project-name/⁨App_Resources⁩/⁨Android**⁩ folder. 
you can get it from: https://developers.google.com/youtube/android/player/downloads/

If this is a required step please add it to the README 
otherwise please tell me where I went wrong :)

**Comment by ihor-lev** [comment]
@mpht: Thanks for your advice.

Unfortunately, it didn't work for me. Also I tried to add the latest YouTubeAndroidPlayerApi.jar (1.2.2) to "node_modules/nativescript-youtubeplayer/platforms/android". Gradle fetched it during the build but the build failed.

**Comment by triniwiz** [comment]
Fixed on `@triniwiz/nativescript-youtubeplayer`
