### ISSUE TITLE
Player View issue and width

### ISSUE THREAD

**Issue by thunder413** [triniwiz/nativescript-youtubeplayer#5]
First thanks for this plugin,

I have a component Player witch receive a video object from another component (List) via navigationExtra when i run it for the first time it play correctly the video but when i press back button and try with another video the player won't show in portrait  only in landscape (i toggle fullscreen mode on orientation change)
Code Sample
```
<ng-container *ngSwitchCase="'youtube'">
        <YoutubePlayer #player id="player" [apiKey]="apiKey" [src]="video.source" height="200" width="100%" ></YoutubePlayer>
    </ng-container>
```
```
This is the part where i get the video object 
this._paramSubscription = this.route.queryParams.subscribe(params => {
            this._video = Video.fromJson(JSON.parse(params['dataItem']));
            console.log("Player >> "+this._video.provider+" | "+this._video.source);
        });
```
And this how i get reference to the player 
 @ViewChild("player") youtubePlayer:ElementRef;

**Comment by triniwiz** [comment]
Which platform ?

**Comment by thunder413** [comment]
android

**Comment by triniwiz** [comment]
can u call `youtubePlayer.destroy()` in the `ngOnDestroy`

**Comment by triniwiz** [comment]
fixed in `@triniwiz/nativescript-youtube`
