### ISSUE TITLE
TypeError: Class constructor View cannot be invoked without 'new'

### ISSUE THREAD

**Issue by SrivardhanDevarakonda** [triniwiz/nativescript-youtubeplayer#57]
I wanted to use the **nativescript-youtubeplayer** /  **nativescript-youtubeplayer-inline** npm package to play youtube videos in my nativescript-angular mobile app. I've followed the steps provided at https://www.npmjs.com/package/nativescript-youtubeplayer
When i'm trying to build my app using **tns run android --bundle** command, I'm facing the below error..

_JS: ERROR Error: Uncaught (in promise): TypeError: Class constructor View cannot be invoked without 'new'
JS: TypeError: Class constructor View cannot be invoked without 'new'
JS:     at new YoutubePlayerBase (file:///data/user/0/org.nativescript.nsngsample/files/app/vendor.js:154484:42)
JS:     at new YoutubePlayer (file:///data/user/0/org.nativescript.nsngsample/files/app/vendor.js:154511:1)
JS:     at ViewUtil.createView (file:///data/user/0/org.nativescript.nsngsample/files/app/vendor.js:93506:22)
JS:     at NativeScriptRenderer.createElement (file:///data/user/0/org.nativescript.nsngsample/files/app/vendor.js:93706:30)
JS:     at elementCreate (file:///data/user/0/org.nativescript.nsngsample/files/app/vendor.js:50479:25)
JS:     at ɵɵelementStart (file:///data/user/0/org.nativescript.nsngsample/files/app/vendor.js:58110:43)
JS:     at Module.ɵɵelement (file:///data/user/0/org.nativescript.nsngsample/files/app/vendor.js:58187:5)
JS:     at AppTabsComponent_Template (file:///data/user/0/org.nativescript.nsngsample/files/app/bundle.js:138:64)..._

Please find below my project details:
Angular CLI: 10.2.0
Node: 12.19.0
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version

@angular-devkit/architect    0.1002.0
@angular-devkit/core         10.2.0
@angular-devkit/schematics   10.2.0
@angular/cli                 10.2.0
@ngtools/webpack             10.1.7
@schematics/angular          10.2.0
@schematics/update           0.1002.0
rxjs                         6.6.3
typescript                   3.9.7

**Package.json:**
{
  "name": "@nativescript/template-hello-world-ng",
  "main": "main.js",
  "version": "7.0.2",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "scripts": {
    "ngcc": "ngcc --properties es2015 module main --first-only",
    "postinstall": "npm run ngcc"
  },
  "dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/cli": "^10.1.7",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.0",
    "@nativescript/schematics": "^10.1.0",
    "@nativescript/theme": "~2.3.0",
    "nativescript-ui-sidedrawer": "^9.0.3",
    "nativescript-youtubeplayer": "^3.0.1",
    "nativescript-youtubeplayer-inline": "^53.0.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~10.1.0",
    "@nativescript/android": "7.0.0",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~10.1.0",
    "typescript": "~3.9.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

**tsconfig.json:**
{
  "compilerOptions": {
      "module": "ESNext",
      "target": "ESNext",
      "moduleResolution": "node",
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "noEmitHelpers": true,
      "noEmitOnError": true,
      "skipLibCheck": true,
      "lib": [
        "es2018", "es2017", "dom", "es6"
      ],
      "baseUrl": ".",
      "paths": {
          "~/*": [
              "app/*"
          ]
      }
  },
  "include": [
    "src/tests/**/*.ts",
    "src/**/*.ios.ts",
    "src/**/*.android.ts"
  ],
  "files": [
    "./references.d.ts",
    "./src/main.ts"
  ],
  "exclude": [
      "node_modules",
      "platforms",
      "e2e"
  ]
}

I tried setting 'target' to 'es5' still facing the issue..
Is this youtube npm package compatible with these versions?
Please let me know how to fix this issue..

**Comment by miladfm** [comment]
Hey,

Nativescript recently introduced some big changes (for example they changed the compiler option from "ES-5" to "ES2017"). It would be great if you could bring the whole project up to date.

Here's the URL with all the instructions: https://nativescript.org/blog/nativescript-7-for-plugin-authors/

Thank you :)

**Comment by SrivardhanDevarakonda** [comment]
@miladfm Thanks for your response. I actually tried as you mentioned but still, I'm facing the same issue.

**Comment by miladfm** [comment]
actually, my comment was for the author of the plugin.
He has to upgrade the plugin to Nativescript 7.

Old Nativescript plugins don't work with the latest version of Nativescript.

The YoutubePlayer plugin is optimized for Nativescript 5 and angular 6. Maybe it's work in Nativescript 6 fine but there are some big changes in Nativescript 7 and angular 10.

you have to wait until the Author of the plugin upgrade it to version 7

**Comment by SrivardhanDevarakonda** [comment]
@romandragan, @triniwiz 
Can we upgrade this plugin to the latest version for compatibility?

**Comment by romandrahan** [comment]
@SrivardhanDevarakonda, I'm not the maintainer of this plugin, but I created a fork and adapted it to NS7: https://www.npmjs.com/package/nativescript-youtubeplayer-inline

You can use it if you want to.

**Comment by SrivardhanDevarakonda** [comment]
@romandragan, I even tried your plugin "nativescript-youtubeplayer-inline" with Angular 10 & NS7, that is when I faced the issue:
JS: ERROR Error: Uncaught (in promise): TypeError: Class constructor View cannot be invoked without 'new'
JS: TypeError: Class constructor View cannot be invoked without 'new'

**Comment by triniwiz** [comment]
Sorry I haven't got around to upgrading this plugin but it's on my plugin todo list I'm trying to finish to release all my new stuff

**Comment by SrivardhanDevarakonda** [comment]
@romandragan @triniwiz any idea on how to temporarily fix these issues (with Angular 9/10 & NS7) until we have latest plugins..
**JS: ERROR Error: Uncaught (in promise): TypeError: Class constructor View cannot be invoked without 'new'
JS: TypeError: Class constructor View cannot be invoked without 'new'**

**Comment by triniwiz** [comment]
You would need to fork and update any ts class extension with the `@NativeClass` decorator as for angular you can use `registerElement` an ignore the module for now

**Comment by SrivardhanDevarakonda** [comment]
@triniwiz, @romandragan  nativescript-youtubeplayer is working fine with Angular 9, Nativescript 6.8.x version.
I'm using a tab view in my mobile application, For eg: there are 2 tabs "Home" & "Other". The Youtube player is working fine in the Home component/outlet. But I want to have a Youtube player in the child component of the "Home" outlet which is not working. I've tried importing **YoutubePlayerModule** in the child component's module. 
Please let me know if I'm missing something.

**Comment by lehongwang** [comment]
please, fix this to able to run on NS7 :((

**Comment by Agostin** [comment]
Same issue here using NS7 with Vue.js! 😞

**Comment by romandrahan** [comment]
Just added NS 7 support to my fork `nativescript-youtubeplayer-inline`. 73.0.1 version should be fine at least for Vue projects.

**Comment by sturzflaviu** [comment]
Hey, @romandragan I'm using your library in a vue project and is working fine when displaying the youtube video, but I don't know how to call the api methods. The old logic that I've used is not working anymore.

This is the import in main.js: 
`Vue.registerElement('YoutubePlayer', () => require('nativescript-youtubeplayer-inline').YoutubePlayer);`

Template Video.vue :
 `<YoutubePlayer  id="youtubeVideo" resumePlayAndroid="false" :src="videoCode" apiKey="AIza***"/>`

 How I'm getting the object :
 `this.currentVideo = this.page.getViewById("youtubeVideo");`

 How I call the methods :
 `this.currentVideo.isPlaying()`
 
 Error : 
 `CONSOLE ERROR: [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
found in
---> <Video> at components/Video.vue`

If I console log "this.currentVideo" I've got this : `YoutubePlayer<youtubeVideo>`

**Comment by romandrahan** [comment]
Hey @sturzflaviu, it's working fine for me like this:

```
<YoutubePlayer
  ref="youtubePlayer"
  ...
/>
```

```
this.$refs.youtubePlayer.nativeView.play()
```

**Comment by sturzflaviu** [comment]
Thank you @romandragan is working now!

**Comment by triniwiz** [comment]
it's under `@triniwiz/nativescript-youtubepayer` decided to rewrite everything
