### ISSUE TITLE
NS7 compatibility

### ISSUE THREAD

**Issue by shilik** [triniwiz/nativescript-youtubeplayer#60]
Thanks for the great plugin, but it broke in NS7. Any plan to upgrade to NS7?

**Comment by triniwiz** [comment]
I’m almost finished with the migration for this plugin

**Comment by mxignas** [comment]
When approximately you are planning to release latest version? @triniwiz

**Comment by triniwiz** [comment]
@mxignas today 😄  it's `@triniwiz/nativescript-youtubeplayer`

**Comment by kryptus36** [comment]
@triniwiz I don't see any commits or releases. How do I get it?

**Comment by triniwiz** [comment]
it's [here](https://github.com/triniwiz/nativescript-plugins/pull/23/commits/24021b91379a58e40f64f9ac13b33e403cc6a322) I moved all the plugins I work on to that new repo so v7+ work would be in there now

**Comment by mxignas** [comment]
how i can import newest version of this plugin while i already have older one? i see your github repo, but how do i import it on my project

**Comment by kryptus36** [comment]
> how i can import newest version of this plugin while i already have older one? i see your github repo, but how do i import it on my project

npm r nativescript-youtubeplayer
npm i @triniwiz/nativescript-youtubeplayer

**Comment by kryptus36** [comment]
> > how i can import newest version of this plugin while i already have older one? i see your github repo, but how do i import it on my project
> 
> npm r nativescript-youtubeplayer
> npm i @triniwiz/nativescript-youtubeplayer

more accurately:
ns plugin remove nativescript-youtubeplayer
ns plugin add @triniwiz/nativescript-youtubeplayer

**Comment by mxignas** [comment]
> > > how i can import newest version of this plugin while i already have older one? i see your github repo, but how do i import it on my project
> > 
> > 
> > npm r nativescript-youtubeplayer
> > npm i @triniwiz/nativescript-youtubeplayer
> 
> more accurately:
> ns plugin remove nativescript-youtubeplayer
> ns plugin add @triniwiz/nativescript-youtubeplayer

im getting error:

ERROR in ./app.js
Module not found: Error: Can't resolve '@triniwiz/nativescript-youtubeplayer' in 'C:\Users\mxign\Desktop\Ignas\University\Third year\Individual project\try2\mobileapp\app'
 @ ./app.js 44:43-90
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'

I removed old plugin, installed this one, changed plugin name, looks like this now:
Vue.registerElement('YoutubePlayer', 
() => require('@triniwiz/nativescript-youtubeplayer').YoutubePlayer)

is there anything else i need to change?

**Comment by kryptus36** [comment]
I'm not a Windows guy but guessing:

 Error from chokidar (C:): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'


Possibly a deadlock. Try rebooting?
