### ISSUE TITLE
"Unrecognized feature: 'picture-in-picture'."

### ISSUE THREAD

**Issue by PashaArkus** [triniwiz/nativescript-youtubeplayer#62]
After updating nativescript to version 7 and updating the plugin, the player stopped working.
The error I'm getting is chromium: [INFO: CONSOLE (629)] "Unrecognized feature: 'picture-in-picture'.", Source: https://www.youtube.com/s/player/490079fb/www-widgetapi .vflset / www-widgetapi.js (629)
![Screenshot_59](https://user-images.githubusercontent.com/51406473/108097345-ae7a9900-708a-11eb-89c9-05df3e052655.png)
![Screenshot_58](https://user-images.githubusercontent.com/51406473/108097349-afabc600-708a-11eb-8f26-ef3d07e75cc3.png)

**Comment by kryptus36** [comment]
Seeing similar behavior running on a physical device.

In my emulator its also showing:
chromium: [ERROR:context_group.cc(136)] ContextResult::kFatalFailure: WebGL1 blacklisted

In both cases, I get an error message in the player and no playback.

**Comment by nickolanack** [comment]
~~^^ Same issue for me~~
 
update: I still see that info/error notice (android) but I had forgotten to add width and height to the player XD. It now works for me

**Comment by PashaArkus** [comment]
Unfortunately it didn't help me

**Comment by kryptus36** [comment]
I am using the simplest markup I think I can. Still no dice.

```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd"
  xmlns:ui="@triniwiz/nativescript-youtubeplayer" loaded="loaded" navigatingTo="navigatingTo" navigatingFrom="navigatingFrom" actionBarHidden='true'>

  <GridLayout id="main-content" rows="*">

    <ui:YoutubePlayer id="player" apiKey="xyz" src="wH_0_pijbZY" height="250" width="500" backgroundColor="gray" />


  </GridLayout>
</Page>
```

**Comment by triniwiz** [comment]
I have an idea what’s happening it’s not loading the videoId after the player is ready a temp work around is to listen for the ready event then set the src

**Comment by PashaArkus** [comment]
Hi, I did as you said, but the problem persists. I created a[ repository](https://github.com/PashaArkus/nativescript_test_youtube) for the test, maybe this information will help you

**Comment by triniwiz** [comment]
`loaded ` doesn't mean the youtube api has been loaded you can try binding to the ready event in the view or directly in code 

```ts
	player.on('ready', () => {
		console.log('onReady');
                /// set the src here
	});

```

**Comment by triniwiz** [comment]
should be good in `4.0.4`

**Comment by Whip** [comment]
I'm still getting this issue on 4.0.4

**Comment by PashaArkus** [comment]
> `loaded ` не означает, что API YouTube был загружен, вы можете попробовать привязать к готовому событию в представлении или непосредственно в коде
> 
> ```ts
> 	игрок . on ( 'ready' ,  ( )  =>  { 
> 		console . log ( 'onReady' ) ; 
>                 /// здесь 
> 	указываем src } ) ;
> ```

unfortunately this option did not help either, I will wait for the plugin update

**Comment by triniwiz** [comment]
Can you share the error you are getting from 

```
	player.on('error', (error) => {
		console.log('onError', error);
	});
```

**Comment by triniwiz** [comment]
So for anyone curious `Unrecognized feature: 'picture-in-picture'.` does not mean the video will not play it's only a warning another thing is you cannot play private videos at the moment. Which means `apiKey` is ignored for now

**Comment by PashaArkus** [comment]
> Can you share the error you are getting from
> 
> ```
> 	player.on('error', (error) => {
> 		console.log('onError', error);
> 	});
> ```

onError {
  "eventName": "error",
  "object": {
    "_observers": {
      "loaded": [
        {}
      ],
      "playing": [
        {}
      ],
      "paused": [
        {}
      ],
      "ended": [
        {}
      ],
      "error": [
        {}
      ]
    },
    "_onLoadedCalled": true,
    "_onUnloadedCalled": false,
    "_cssState": {
      "viewRef": {},
      "_matchInvalid": false,
      "_match": {
        "changeMap": {},
        "selectors": []
      },
      "_appliedSelectorsVersion": 3100000,
      "_appliedChangeMap": "[Circular]",
      "_appliedPropertyValues": {},
      "_playsKeyframeAnimations": false
    },
    "pseudoClassAliases": {
      "highlighted": [
        "active",
        "pressed"
      ]
    },
    "cssClasses": {},
    "cssPseudoClasses": {},
    "_domId": 274,
    "_style": {
      "_observers": {},
      "unscopedCssVariables": {},
      "scopedCssVariables": {},
      "viewRef": {}
    },
    "_gestureObservers": {},
    "__vue_element_ref__": {
      "nodeType": 1,
      "_tagName": "nativeyoutubeplayer",
      "parentNode": {
        "nodeType": 1,
        "_tagName": "nativestacklayout",
        "parentNode": {
          "nodeType": 1,
          "_tagName": "nativepage",
          "parentNode": null,
          "childNodes": [
            {
              "nodeType": 1,
              "_tagName": "nativeactionbar",
              "parentNode": "[Circular]",
              "childNodes": [
                {
                  "nodeType": 1,
                  "_tagName": "nativenavigationbutton",
                  "parentNode": "[Circular]",
                  "childNodes": [],
                  "prevSibling": null,
                  "nextSibling": {
                    "nodeType": 1,
                    "_tagName": "nativegridlayout",
                    "parentNode": "[Circular]",
                    "childNodes": [
                      {
                        "nodeType": 1,
                        "_tagName": "nativelabel",
                        "parentNode": "[Circular]",
                        "childNodes": [],
                        "prevSibling": null,
                        "nextSibling": {
                          "nodeType": 1,
                          "_tagName": "nativebutton",
                          "parentNode": "[Circular]",
                          "childNodes": [],
                          "prevSibling": "[Circular]",
                          "nextSibling": null,
                          "_ownerDocument": null,
                          "_nativeView": {
                            "_observers": {
                              "tap": [
                                {}
                              ]
                            },
                            "_onLoadedCalled": true,
                            "_onUnloadedCalled": false,
                            "_cssState": {
                              "viewRef": {},
                              "_matchInvalid": false,
                              "_match": {
                                "changeMap": {},
                                "selectors": [
                                  {
                                    "cssClass": "far",
                                    "ruleset": {
                                      "selectors": [
                                        "[Circular]"
                                      ],
                                      "declarations": [
                                        {
                                          "property": "font-family",
                                          "value": "\"Font Awesome 5 Pro\", \"fa-regular-400\""
                                        },
                                        {
                                          "property": "font-weight",
                                          "value": "400"
                                        }
                                      ]
                                    },
                                    "pos": 1
                                  },
                                  {
                                    "cssClass": "action_bar",
                                    "ruleset": {
                                      "selectors": [
                                        "[Circular]"
                                      ],
                                      "declarations": [
                                        {
                                          "property": "background-color",
                                          "value": "#888888"
                                        }
                                      ]
                                    },
                                    "pos": 19
                                  },
                                  {
                                    "cssClass": "action_bar_btn_back",
                                    "ruleset": {
                                      "selectors": [
                                        "[Circular]"
                                      ],
                                      "declarations": [
                                        {
                                          "property": "color",
                                          "value": "#FFFFFF"
                                        },
                                        {
                                          "property": "font-size",
                                          "value": "20"
                                        },
                                        {
                                          "property": "width",
                                          "value": "48"
                                        },
                                        {
                                          "property": "border-color",
                                          "value": "transparent"
                                        },
                                        {
                                          "property": "border-width",
                                          "value": "1"
                                        },
                                        {
                                          "property": "z-index",
                                          "value": "0"
                                        },
                                        {
                                          "property": "margin-right",
                                          "value": "10"
                                        }
                                      ]
                                    },
                                    "pos": 27
                                  },
                                  {
                                    "cssClass": "far",
                                    "ruleset": {
                                      "selectors": [
                                        "[Circular]"
                                      ],
                                      "declarations": [
                                        {
                                          "property": "font-family",
                                          "value": "\"Font Awesome 5 Pro\", \"fa-regular-400\""
                                        },
                                        {
                                          "property": "font-weight",
                                          "value": "400"
                                        }
                                      ]
                                    },
                                    "pos": 559
                                  },
                                  {
                                    "cssClass": "action_bar",
                                    "ruleset": {
                                      "selectors": [
                                        "[Circular]"
                                      ],
                                      "declarations": [
                                        {
                                          "property": "background-color",
                                          "value": "#141414"
                                        }
                                      ]
                                    },
                                    "pos": 577
                                  },
                                  {
                                    "cssClass": "action_bar_btn_back",
                                    "ruleset": {
                                      "selectors": [
                                        "[Circular]"
                                      ],
                                      "declarations": [
                                        {
                                          "property": "color",
                                          "value": "#FFFFFF"
                                        },
                                        {
                                          "property": "font-size",
                                          "value": "20"
                                        },
                                        {
                                          "property": "width",
                                          "value": "48"
                                        },
                                        {
                                          "property": "border-color",
                                          "value": "transparent"
                                        },
                                        {
                                          "property": "border-width",
                                          "value": "1"
                                        },
                                        {
                                          "property": "z-index",
                                          "value": "0"
                                        },
                                        {
                                          "property": "margin-right",
                                          "value": "10"
                                        }
                                      ]
                                    },
                                    "pos": 585
                                  }
                                ]
                              },
                              "_appliedSelectorsVersion": 3100000,
                              "_appliedChangeMap": "[Circular]",
                              "_appliedPropertyValues": {
                                "font-family": "\"Font Awesome 5 Pro\", \"fa-regular-400\"",
                                "font-weight": "400",
                                "background-color": "#141414",
                                "color": "#FFFFFF",
                                "font-size": "20",
                                "width": "48",
                                "border-color": "transparent",
                                "border-width": "1",
                                "z-index": "0",
                                "margin-right": "10"
                              },
                              "_playsKeyframeAnimations": false
                            },
                            "pseudoClassAliases": {
                              "highlighted": [
                                "active",
                                "pressed"
                              ]
                            },
                            "cssClasses": {},
                            "cssPseudoClasses": {},
                            "_domId": 272,
                            "_style": {
                              "_observers": {},
                              "unscopedCssVariables": {},
                              "scopedCssVariables": {},
                              "viewRef": {}
                            },
                            "_gestureObservers": {},
                            "_tappable": false,
                            "__vue_element_ref__": "[Circular]",
                            "_isLayoutValid": false,
                            "parent": {
                              "_observers": {},
                              "_onLoadedCalled": true,
                              "_onUnloadedCalled": false,
                              "_cssState": {
                                "viewRef": {},
                                "_matchInvalid": false,
                                "_match": {
                                  "changeMap": {},
                                  "selectors": []
                                },
                                "_appliedSelectorsVersion": 3100000,
                                "_appliedChangeMap": "[Circular]",
                                "_appliedPropertyValues": {},
                                "_playsKeyframeAnimations": false
                              },
                              "pseudoClassAliases": {
                                "highlighted": [
                                  "active",
                                  "pressed"
                                ]
                              },
                              "cssClasses": {},
                              "cssPseudoClasses": {},
                              "_domId": 270,
                              "_style": {
                                "_observers": {},
                                "unscopedCssVariables": {},
                                "scopedCssVariables": {},
                                "viewRef": {}
                              },
                              "_gestureObservers": {},
                              "_subViews": [
                                {
                                  "_observers": {},
                                  "_onLoadedCalled": true,
                                  "_onUnloadedCalled": false,
                                  "_cssState": {
                                    "viewRef": {},
                                    "_matchInvalid": false,
                                    "_match": {
                                      "changeMap": {},
                                      "selectors": [
                                        {
                                          "cssClass": "action_title",
                                          "ruleset": {
                                            "selectors": [
                                              "[Circular]"
                                            ],
                                            "declarations": [
                                              {
                                                "property": "color",
                                                "value": "#FFFFFF"
                                              },
                                              {
                                                "property": "font-size",
                                                "value": "16"
                                              },
                                              {
                                                "property": "font-family",
                                                "value": "\"Roboto Bold\", sans-serif"
                                              },
                                              {
                                                "property": "font-weight",
                                                "value": "bold"
                                              },
                                              {
                                                "property": "text-transform",
                                                "value": "uppercase"
                                              }
                                            ]
                                          },
                                          "pos": 18
                                        },
                                        {
                                          "cssClass": "action_title",
                                          "ruleset": {
                                            "selectors": [
                                              "[Circular]"
                                            ],
                                            "declarations": [
                                              {
                                                "property": "color",
                                                "value": "#FFFFFF"
                                              },
                                              {
                                                "property": "font-size",
                                                "value": "16"
                                              },
                                              {
                                                "property": "font-family",
                                                "value": "\"Roboto Bold\", sans-serif"
                                              },
                                              {
                                                "property": "font-weight",
                                                "value": "bold"
                                              },
                                              {
                                                "property": "text-transform",
                                                "value": "uppercase"
                                              }
                                            ]
                                          },
                                          "pos": 576
                                        }
                                      ]
                                    },
                                    "_appliedSelectorsVersion": 3100000,
                                    "_appliedChangeMap": "[Circular]",
                                    "_appliedPropertyValues": {
                                      "color": "#FFFFFF",
                                      "font-size": "16",
                                      "font-family": "\"Roboto Bold\", sans-serif",
                                      "font-weight": "bold",
                                      "text-transform": "uppercase"
                                    },
                                    "_playsKeyframeAnimations": false
                                  },
                                  "pseudoClassAliases": {
                                    "highlighted": [
                                      "active",
                                      "pressed"
                                    ]
                                  },
                                  "cssClasses": {},
                                  "cssPseudoClasses": {},
                                  "_domId": 271,
                                  "_style": {
                                    "_observers": {},
                                    "unscopedCssVariables": {},
                                    "scopedCssVariables": {},
                                    "viewRef": {}
                                  },
                                  "_gestureObservers": {},
                                  "_tappable": false,
                                  "__vue_element_ref__": "[Circular]",
                                  "_isLayoutValid": false,
                                  "parent": "[Circular]",
                                  "_styleScope": {
                                    "_css": "",
                                    "_localCssSelectors": [],
                                    "_localCssSelectorVersion": 0,
                                    "_localCssSelectorsAppliedVersion": 0,
                                    "_applicationCssSelectorsAppliedVersion": 31,
                                    "_keyframes": {
                                      "translate-data-v-286f1e53": {
                                        "type": "keyframes",
                                        "name": "translate-data-v-286f1e53",
                                        "keyframes": [
                                          {
                                            "type": "keyframe",
                                            "declarations": [
                                              {
                                                "type": "declaration",
                                                "property": "transform",
                                                "value": "translate(0, 100)",
                                                "position": {
                                                  "start": {
                                                    "line": 40,
                                                    "column": 5
                                                  },
                                                  "end": {
                                                    "line": 40,
                                                    "column": 33
                                                  },

**Comment by triniwiz** [comment]
Sorry it's error.error 🙂

**Comment by PashaArkus** [comment]
> Sorry it's error.error 🙂

onError 2

**Comment by PashaArkus** [comment]
![Screenshot_2021-03-08-08-59-35-504_ua com getmancar](https://user-images.githubusercontent.com/51406473/110286138-1585d080-7fed-11eb-8612-dfaa00f98811.jpg)
Here is an error on the screen that says there is an error, try again later. Playback indicator: .... In this case, if I click on the indicator in the lower right corner, the mobile version of the youtube site opens
![Screenshot_2021-03-08-09-06-49-170_ua com getmancar](https://user-images.githubusercontent.com/51406473/110286716-0bb09d00-7fee-11eb-949e-6dbf99e68503.jpg)
But the video is not what was expected

**Comment by triniwiz** [comment]
What videoId are you trying also what's the link the video ?

**Comment by PashaArkus** [comment]
any video

**Comment by triniwiz** [comment]
Can you share the id(s) you're trying?

**Comment by PashaArkus** [comment]
hUuRlnM0IYY or ZXi_iXMMU_I or https://www.youtube.com/watch?v=FCyoHclCqc8, any

**Comment by triniwiz** [comment]
Another thing since you're using v7 it's now videoId not src and it's only taking the videoId check the [docs](https://triniwiz.github.io/nativescript-plugins/api-reference/youtube-player.html#api)

**Comment by PashaArkus** [comment]
I tried videoId, the result is the same. I also tried the [link](https://triniwiz.github.io/nativescript-plugins/api-reference/youtube-player.html#configuration) and step by step adding the plugin to the project as indicated in the documentation, that is, there are also errors describing the plugin connection.

![Screenshot_11](https://user-images.githubusercontent.com/51406473/110498869-60dcd380-8100-11eb-9cbe-5c8051d8a116.png)

 I also tried reinstalling the android platform, it didn't work either

this is how i import the plugin in app.js
![Screenshot_13](https://user-images.githubusercontent.com/51406473/110499111-9aadda00-8100-11eb-98f4-0ee645d281e3.png)

this is how i display it on the page
![Screenshot_14](https://user-images.githubusercontent.com/51406473/110499328-ca5ce200-8100-11eb-947f-a5112d223c87.png)

**Comment by kryptus36** [comment]
I don't know if it's helpful, but here's an observation from my using it with NS core on an Android emulator:

If I attempt to use:
    <yt:YoutubePlayer id="youTube" loaded="onYouTubeLoaded" ready="onYouTubeReady" stateChange="onYouTubeStateChanged" apiReady="onYouTubeAPIReady" videoId="qUUloBe5vEo" showRelatedVideos="false" showYoutubeLogo="false" showFullScreenToggle="false" controls="false"/>

The only event I see fire is onYouTubeLoaded

In there, I can programmatically set events that fire correctly.

```
export function onYouTubeLoaded(args: any) {
  console.log('yt loaded');
  const youTube = args.object;

  youTube.on('ready', (args: any) => {
    console.log('this fires as expected');
  });
```

**Comment by triniwiz** [comment]
What about `error="onError"` ?

**Comment by kryptus36** [comment]
I set  error="onYouTubeError" and

export function onYouTubeError(args: any) {
  console.log('yt error');
}

never fired even when intentionally setting videoId to be invalid and calling play();

Outside these binding issues, the player is working great for me.

**Comment by PashaArkus** [comment]
somehow the plugin worked, maybe due to the fact that I reinstalled the platform, but I'm not sure about that. Thanks for the help
