### ISSUE TITLE
NEW FEATURE - Event when video ends.

### ISSUE THREAD

**Issue by glen-stephens** [triniwiz/nativescript-youtubeplayer#7]
Please add an event that fires when video stops playing.

**Comment by glen-stephens** [comment]
Tested on Android and it works, iOS does not work.

**Comment by Xsmael** [comment]
+1

**Comment by rg777** [comment]
Is there any update on this?

**Comment by triniwiz** [comment]
Available on `@triniwiz/nativescript-youtubeplayer`
