### ISSUE TITLE
NEW FEATURE - Event when exiting full screen

### ISSUE THREAD

**Issue by glen-stephens** [triniwiz/nativescript-youtubeplayer#8]
If possible, add an event that fires when the player exits full screen.

**Comment by glen-stephens** [comment]
Tested on Android and it work, iOS does not work.

**Comment by EdJones** [comment]
> 
> 
> Tested on Android and it work, iOS does not work.

@glen-stephens Did you find a solution?

**Comment by triniwiz** [comment]
Available on `@triniwiz/nativescript-youtubeplayer`
